# config/meta.yml

meta_product_name: “The Favorite”

meta_title: “The Favorite – Parents' duties manager”

meta_description: “Take care of your child, organize his activities and much more... And above all, collect points to beat the other parent and become the favorite! ”

meta_image: "cover.png" # should exist in `app/assets/images/`
